name: (Build) - Build windows/mac/linux bundles

on:
  workflow_call:
    inputs:
      target_ref:
        required: true
        type: string
      build_type:
        required: false
        type: string
        default: release
      godot_version:
        required: false
        type: string
        default: 4.4.1

permissions:
  contents: write

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:${{ inputs.godot_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.target_ref }}'
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable ~/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable
      - name: Add version data
        run: |
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          git config --global --add safe.directory /__w/PNGTuber-Remix/PNGTuber-Remix
          git describe --tags --exclude nightly --always > "$EXPORT_DIR/windows/.version"
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/PNGTuber-Remix.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows
          include-hidden-files: true

  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:${{ inputs.godot_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.target_ref }}'
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable ~/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          git config --global --add safe.directory /__w/PNGTuber-Remix/PNGTuber-Remix
          git describe --tags --exclude nightly --always > "$EXPORT_DIR/linux/.version"
          godot --headless --verbose --export-release "Linux/X11" "$EXPORT_DIR/linux/PNGTuber-Remix.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
          include-hidden-files: true

  export-mac:
    if: false
    name: Mac Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:${{ inputs.godot_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: '${{ inputs.target_ref }}'
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable ~/.local/share/godot/export_templates/${{ inputs.godot_version }}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          EXPORT_DIR="$(readlink -f build)"
          git config --global --add safe.directory /__w/PNGTuber-Remix/PNGTuber-Remix
          git describe --tags --exclude nightly --always > "$EXPORT_DIR/mac/.version"
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/PNGTuber-Remix.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: build/mac
          include-hidden-files: true
